version: '3'
services:
  couch:
    build:
      context: ./couch
      args:
        HOST: "${HOST}"
        COUCH_ADMIN: "${COUCH_ADMIN}"
        COUCH_ADMIN_PASSWORD: "${COUCH_ADMIN_PASSWORD}"
    ports:
      - '5984:5984'
