version: '3'
services:
  couch:
    build:
      context: ./couch
      args:
        HOST: "${HOST}"
        COUCH_ADMIN: "${COUCH_ADMIN}"
        COUCH_ADMIN_PASSWORD: "${COUCH_ADMIN_PASSWORD}"
    volumes:
      - ./couch:/couch
    ports:
      - '5984:5984'
  server:
    build:
      context: ./server
      args:
        NODE_ENV: development
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./server/package.json:/app/package.json
      - ./server/yarn.lock:/app/yarn.lock
      - ./server/src:/app/src
    ports:
      - '8200:8200'

volumes:
  yarn: